version: '3'

services:
  explorer-server:
    container_name: 'explorer-server'
    image: 'explorer-server'
    ports: ['8001:8000']
  geth-client:
    container_name: 'geth-client'
    image: 'ethereum/client-go'
    ports: ['30303:30303', '8545:8545']
    volumes: ['/Users/jmunsch/.lamden/newCoin:/root/.ethereum']
    build:
        context: ./go-ethereum
        dockerfile: Dockerfile
  # lamden-api:
  #   container_name: 'lamden-api'
  #   image: 'lamden-api'
  #   ports: ['9001:9001']
  #   labels: ['com.lamden.role=api']
#   mongodb:
#     image: 'bitnami/mongodb:latest'
#     volumes:
#       - 'mongodb_data:/bitnami'
#   parse:
#     image: 'bitnami/parse:latest'
#     labels:
#       kompose.service.type: nodeport
#     ports:
#       - '1337:1337'
#     volumes:
#       - 'parse_data:/bitnami'
#     depends_on:
#       - mongodb
#   raiden:
#     container_name: 'raiden'
#     image: 'raiden'
#     ports: ['40001:8003']
#   remix:
#     container_name: 'remix'
#     image: 'remix'
#     ports: ['8080:8004']
# volumes:
#   mongodb_data:
#     driver: local
#   parse_data:
#     driver: local
